### ISSUE TITLE
energy

### ISSUE THREAD

**Issue by Choopanian-Peyman** [mxfold/mxfold2#13]
Hi,

What does the number inside the bracket show?
I mean output from 'mxfold2 predict'.
Is it the energy of the secondary structure?
Or how can I extract energy from it?

Best,
Peyman

**Comment by satoken** [comment]
It is the folding score, which corresponds to Eq. (1) in the paper (http://dx.doi.org/10.1038/s41467-021-21194-4). A large value means a stable structure. If you need the free energy of the predicted secondary structure, you can use RNAeval in ViennaRNA pacakge (http://rna.tbi.univie.ac.at/cgi-bin/RNAWebSuite/RNAeval.cgi).

**Comment by Choopanian-Peyman** [comment]
Thank you @satoken
